### ISSUE TITLE
Automation bot hasn't filed a PR for MLflow 2.1.1

### ISSUE THREAD

**Issue by harupy** [conda-forge/mlflow-feedstock#112]
We released [MLflow 2.1.1](https://pypi.org/project/mlflow/2.1.1) on PyPI on Dec 26, 2022, but the automation bot hasn't filed a PR for this release yet. The bot normally does within a day after we upload a new version on PyPI.

cc @xhochy

**Comment by harupy** [comment]
cc @WeichenXu123 @dbczumar

**Comment by dbczumar** [comment]
Hi @xhochy , can you take a look / advise here? Thank you!

**Comment by bollwyvl** [comment]
Looking on PyPI, there is no `.tar.gz` for this version:

https://pypi.org/project/mlflow/2.1.1/#files

Perhaps by uploading one, the bot will revisit it, but at present it says (from https://conda-forge.org/status)

```
The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!

Please check the URLs in your recipe with version '2.1.1' to make sure they exist!

We also found the following errors:

 - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'
```

**Comment by dbczumar** [comment]
> Looking on PyPI, there is no `.tar.gz` for this version:
> 
> https://pypi.org/project/mlflow/2.1.1/#files
> 
> Perhaps by uploading one, the bot will revisit it, but at present it says (from https://conda-forge.org/status)
> 
> ```
> The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!
> 
> Please check the URLs in your recipe with version '2.1.1' to make sure they exist!
> 
> We also found the following errors:
> 
>  - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'
> ```

@bollwyvl Thanks so much for identifying the problem here! We'll get that resolved :)

**Comment by harupy** [comment]
@bollwyvl Thanks! Where can I find the following log? Would you mind sharing the URL if it exists?

```
The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!

Please check the URLs in your recipe with version '2.1.1' to make sure they exist!

We also found the following errors:

 - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'
```

**Comment by harupy** [comment]
@bollwyvl Never mind my comment above. I found it.

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/17039389/212445377-8a8401c0-8446-480b-b068-7b6d43cc9781.png">

**Comment by harupy** [comment]
@bollwyvl We uploded `.tar.gz` last week. When will the bot revisit it?

**Comment by bollwyvl** [comment]
It may have gotten discouraged and given up, and need to be refreshed as a manual PR.

**Comment by dbczumar** [comment]
> It may have gotten discouraged and given up, and need to be refreshed as a manual PR.

Thanks @bollwyvl . Is there a guide / tutorial for this? Alternatively, @xhochy, can you re-run the bot?

**Comment by bollwyvl** [comment]
Likely it will boil down to making a PR (can even be in-browser) with updates to:

- `{% set version = 'XX.YY.ZZ' %}`
- `sha256: ABC1234`

After submitting that, have a look at the check list, especially making a comment about asking for a re-render. 

CI will then run, and any further dependency change issues should get called out by various checks and tests... have a look at historical PRs on this repo for other things that might need to change (compiler flags, etc).

**Comment by harupy** [comment]
https://github.com/conda-forge/mlflow-feedstock/pull/113 was filed yesterday. We can close this issue. @bollwyvl Thanks for the support!
