### ISSUE TITLE
Pydantic must be pinned < 2

### ISSUE THREAD

**Issue by jonashaag** [conda-forge/mlflow-feedstock#140]
https://github.com/mlflow/mlflow/blob/2f9285a1c9635778f95c5cf767f5621442545f0b/requirements/gateway-requirements.txt#L5

I can send a PR soon

**Comment by harupy** [comment]
We pin pydantic because we haven't tested the gateway features with pydantic 2.0.

**Comment by jonashaag** [comment]
I won't have time to fix this in the next days, but with 2.6 `import mlflow` is broken if you have anything in the environment that installs `pydantic >=2`
