### ISSUE TITLE
Split JS and CSS map files into a UI debug package

### ISSUE THREAD

**Issue by xhochy** [conda-forge/mlflow-feedstock#8]
As mentioned in https://github.com/mlflow/mlflow/pull/1409, the JS and CSS map files that contain a lot of debug information make up most of the package size and are not needed in most cases. Thus I would like to transform this feedstock into a recipe with two outputs `mlflow` which contains everything except the `.map` files and `mlflow-ui-dbg` which only contains the `.map` files. Thanks to conda's `output:` support, splitting the packages up is much simpler than for Wheels/sdists.

@jaroslawk @andrewmchen Any concerns? Otherwise I would prepare a PR for this.

**Comment by jaroslawk** [comment]
@xhochy I got no concerns with this approach. I would just dump those files but it is ok to have an option to install them on demand as @smurching mention.

Please go ahead create PR - I am back from vacation and should be more responsive.
