### ISSUE TITLE
[Question] Is it ok to add a github actions workflow?

### ISSUE THREAD

**Issue by harupy** [conda-forge/mlflow-feedstock#86]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

This is not an issue but a question. Is it ok to add a GitHub Actions workflow? cc @xhochy 

I'd like to add a test to ensure `recipe/meta.yaml` has the same dependencies as `setup.py` in the mlflow repository.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by xhochy** [comment]
No, Github Actions is reserved for conda-forge's automation and we don't want to have other actions on the repos due to the limited resources available.

**Comment by xhochy** [comment]
We use `pip check` for consistency checks. This is not as good as the perfect check but we also have the `bot.run_deps_from_wheel: true` option for the `conda-forge.yaml`. Sadly this doesn't work due to the complexity of the `mlflow` package. I have been manually the dependencies syncing for now.

**Comment by harupy** [comment]
Got it, thanks for the explanation!
